name: Release Build

on:
  push:
    tags:
      - 'v*.*.*'
  
jobs:
  osx-build:
    name: Build OSX Release Asset
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build project # This would actually build your project, using zip for an example artifact
        run: |
          cd electrum |
          ./contrib/osx/make_osx
          zip -r osx.zip dist
      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: osx.zip
          
  linux-build:
    name: Build Linux Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Enter Code Directory
        run: cd electrum
        
      - name: Install Dependencies
        run: sudo docker build -t electrum-appimage-builder-img contrib/build-linux/appimage
        
      - name: Build project
        run: sudo docker run --name electrum-appimage-builder-cont -v $PWD:/opt/electrum --rm --workdir /opt/electrum/contrib/build-linux/appimage electrum-appimage-builder-img ./build.sh

      - name: Zip Files
        run: zip -r linux.zip dist

      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: linux.zip

  windows-build:
    name: Build Windows Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Enter Code Directory
        run: cd electrum
        
      - name: Install Dependencies
        run: sudo docker build -t electrum-wine-builder-img contrib/build-wine
        
      - name: Build project
        run: sudo docker run --name electrum-wine-builder-cont -v $PWD:/opt/wine64/drive_c/electrum --rm --workdir /opt/wine64/drive_c/electrum/contrib/build-wine electrum-wine-builder-img ./build.sh

      - name: Zip Files
        run: zip -r windows.zip ./contrib/build-wine/dist

      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: windows.zip
